on: [push]

name: build

jobs:
  build_sonar_scanner:
    name: Build sonar-scanner with java 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build sonar-scanner Docker Images
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 4 
        tags: sonar-scanner sonar-scanner:4 sonar-scanner:4.3 sonar-scanner:4.3.0 sonar-scanner:4.3.0.2102 
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
